// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Kv {
    #[prost(bytes = "vec", tag = "1")]
    pub key: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub value: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReadSet {
    #[prost(message, repeated, tag = "2")]
    pub kvs: ::prost::alloc::vec::Vec<Kv>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WriteSet {
    /// upsert
    #[prost(message, repeated, tag = "2")]
    pub upsert_kvs: ::prost::alloc::vec::Vec<Kv>,
    /// delete
    #[prost(bytes = "vec", repeated, tag = "3")]
    pub deleted_keys: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
